name: PR Linting

on:
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          subjectPattern: ^(?![A-Z]).+$
